# 11.1 배열 데이터를 효과적으로 다루는 Numpy

- Numpy는 파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지
- Numpy르 이용하면 파이썬의 기본 데이터 형식과 내장 함수를 이용하는 것보다 다차원 배열 데이터를 효과적으로 처리할 수 있다.
- NumPy 홈페이지(http:www.numpy.org)

## 배열 생성하기
- 설치된 NumPy룰를 이용하려면 먼저 NumPy 패키지를 불러 와야함
- NumPy패키지를 불러올 때 `import numpy as np로 불러온다.

In [1]:
import numpy as np

- 배열(Array)이란 순서가 있는 같은 종류의 데이터가 저정된 집합을 말함
- NumPy를 이용해 배열을 처리하기 위해서는 우선 NumPy로 배열을 생성

## 시퀀스 데이터로부터 배열 생성
- 시퀀스데이터로 NumPy의 배열을 생성하는 방법
- orr_obj = np.array(seq_data)
- 시퀀스 데이터(seq_data)를 인자로 받아NumPy의 배열 객체(array object)를 생성
- 시퀀스 데이터로 리스트와 튜플 타입의 데이터를 모두 사용할 수 있지만 주로 리스트 데이터를 이용
- 리스트로 부터 NumPy의 1차원 배열을 생성

In [2]:
import numpy as np

data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

- 리스트 데이터(data1)를 NumPy의 array()인자로 넣어서 NumPy배열을 만들었음
- 정수와 실수가 혼합된 리스트 데이터로 NumPy배열

In [6]:
data2 = [0,1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0. ,  1. ,  5. ,  4. , 12. ,  0.5])

-NumPy에서 인자로 정수와 실수가 혼합돼 잇을 때 모두 실수로 변환
- NumPy 배열의 속성을 표현하려면 `ndarray 속성`같이 작성
- ndarray는 NumPy의 배열 객체
- 배열 객체의 타입을 확인

In [4]:
a1.dtype # 배열 안에 있는 값의 타입 확인

dtype('int64')

In [5]:
type(a1)# a1의 타입 확인

numpy.ndarray

In [7]:
a2.dtype

dtype('float64')

- 기존 32비트 정수 타입(int32)이고, a2는 64비트 실수 타입(float64)
- 리스트 data1과 data2를 NumPy array()의 인자로 넣어서 NumPy의 배열
- array()에 리스트 데이터를 직접 넣어서 배열 객체를 생성

In [8]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

np는 다차원 배열도 생성할 수 있다.

In [9]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- 2차원 배열을 표시
 - NumPy에서는 1차원 뿐만 아니라 다차원 배열도 생성

## 범위를 지정해 배열 생성
- 범위를 지정해 NumPy 배열을 생성하는 방법
- arr_obj = np.arange([start,],stop[,step])
- start부터 시작해서 stop전까지 step만큼 겸속 더해 NumPy의 배열을 생성
- step이 1인 경우에는 생략할 수 있어서 `numpy.arange(start, stop)`처럼 
- start가 0인 경우에는 start도 생략하고 `numpy.arange(stop)`처럼 사용

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

- NumPy 배열의 arange()를 이용해 생성한 1차원 배열에 `.reshape(m,n)`을 추가하면 mxn형태의 2차원 배열(행렬)로 변경
- mxn 행렬의 구조
- NumPy 배열에서 행과 열의 위치는 각각 0부터 시작

In [13]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- arange(12)로 12개의 숫자를 생성한 후 reshape(4,3)으로 4x3godfuf
- arange()로 생서되는 배열의 원소 개수와 reshape(m,n)의 mxn 개수는 같아야함
- NumPy배열의 형태를 알기 위해서는 `ndarray.shape`를 실행

In [14]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

- b1에는 `reshape(4,3)`을 통해 만들어진 4x3 행렬이 할당
- mxn 행렬(2차원 배열)의 경우에는 `ndarray.shape`를 수행하면 `(m,n)`처럼 표시
- 4x3 행렬인 b1의 경우 `b1.shape`을 수행하면 (4,3)이 출력
- n개의 요소를 갖는 1차원 배열의 경우에는 `ndarray.shape`를 수행하면 `(n,)`처럼 표시

In [15]:
b2 = np.arange(5)
b2.shape

(5,)

- 생성한 변수 b1에는 5개의 요소를 갖는 1차원 배열이 할당돼 있으므로
- `b2.shape`을 수행하면 결과로 (5,)가 나옴
- 범위의 시작과 끝을 지정하고 데이터의 개수를 지정해 NumPy 배열을 생성하는 linspace()
- arr_obj = np.linspace(start,stop,[,num])
- linspace()는 start부터 stop까지 num개의 NumPy배열을 생성
- num을 지정하지 않으면 50으로 간주
- 1부터 10까지의 10개의 데이터를 생성

In [21]:
 np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- 지정된 범위(1~10)에 해당하는 10개의 데이터가 잘 생성
- 0부터 파이까지 동일한 간격으로 나눈 20개의 데이터를 생성

In [22]:
np.linspace(1,np.pi,20)

array([1.        , 1.1127154 , 1.22543081, 1.33814621, 1.45086161,
       1.56357701, 1.67629242, 1.78900782, 1.90172322, 2.01443863,
       2.12715403, 2.23986943, 2.35258483, 2.46530024, 2.57801564,
       2.69073104, 2.80344645, 2.91616185, 3.02887725, 3.14159265])

- 사용한 `np.pi`는 NumPy에서 파이를 입력할 때 사용

## 특별한 형태의 배열 생성
- 특별한 형태의 배열을 생성하는 방법
- 모든 원소가 0혹은 1인 다차원 배열을 만들기 위해서는 zeros()와 ones()를 이용
- arr_zero_n=np.zeros(n)
- arr_zero_mxn = np.zeros((m,n))
- arr_one_n= np.ones(n)
- arr_one_mxn = np.ones((m,n))
- zeros()는 모든 원소가 0, ones()는 모든 원소가 1 인 다차원 배열을 생성
- n개의 원소가 모두 0을 갖는 1차원 배열을 만들려면 np.zeros(n)
- 모든 원소가 -0인 mxn 형태의 2차원 배열(행렬)을 생성하려면 np.zeros((m,n))을 이용
- ones()도 마찬가지로 np.ones(n)과 np.ones((m,n))을 이용
- zeros()함수로 원소의 개수가 10개(n=10)인 1차원 배열을 생성

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
# zeros()을 이용해 3x4의 2차원 배열을 생성
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
#ones()으로 1차원 배열과 2차원 배열을 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.

    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.

    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.


    Examples
    --------
    >>> np.ones(5)
    array([1., 1., 1., 1., 1.])

    >>> np.ones((5,), dtype=int)
    array([1, 1, 1, 1, 1])

    >>> np.ones((2, 1))
    array([[1.],
           [1.]])

    >>> s = (2,2)
    >>> np.ones(s)
    array([[1.,  1.],
           [1.,  1.]])

 - 단위 행렬을 생성하는 방법
 - 단위행렬은 nxn인 정사형 행렬에서 주 대각선이 모두 1이고 나머지는 0인 행렬을 의미
 -  arr_I=np.eye(n)
 - nxn 의 단위행렬을 갖는 2ㅏ원 배열 객체를 생성

In [35]:
#3x3 단위행렬을 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 배열의 데이터 타입 변환
 - NumPy의 배열은 숫자뿐만 아니라 문자열도 원소로 가질 수 있음
 - 문자열이 원소인 NumPy 배열을 생성

In [36]:
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

- dtype은 NumPy 데이터 형식(타입)을 표시
- `dtype = <U8`의 의미는NumPy 데이터 형식이 유니코드이며 문자의 수는 최대 8개라는 것
- NumPy 배열이 문자열(숫자 표시)로 돼 있다면 연산을 위해서는 문자열을 숫자(정수나 실수)로 변환 
- NumPy 배열의 형 변환은 astype()으로 할 수 있음
- num_arr = str_arr.astype(dtype)

- NumPy 배열의 모든 요소를 지정한 데이터 타입(dtype)으로 변환
- 정수나 실수를 문자열로 변환할 수도 있음
- 정수로 바꾸려면 dtype에 int를 입력하고 , 실수로 바꾸려면 float를 입력하며, 문자열로 바꾸려면 str을 입력

In [38]:
# 실수가 입력된 문자열을 원소로 갖는 NumPy배열을 실수 타입으로 변환
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [39]:
#narray.dtype을 이용해 NumPy의 데이터 타입을 확인
str_a1.dtype

dtype('<U5')

In [40]:
#변환한 num_a1의 NumPy의 테이터 타입을 확인
num_a1.dtype

dtype('float64')

- 변수 str_a1은 유니코드(U)였는데 변수num_a1은 dtype이 실수로 변경 된 것

In [44]:
#정수를 문자열로 갖는 NumPy배열을 전수로 변환
str_a2 = np.array(['1','2','3','4','5'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 2, 3, 4, 5])

In [43]:
#str_a2의 데이터 타입
str_a2.dtype

dtype('<U1')

In [45]:
#num_a2의 데이터 타입 (변경후)
num_a2.dtype

dtype('int64')

 - 배열의 데이터 타입이 유니코드(U)에서 정수 타입(int)으로 변경 된 것을 알 수 있음

In [46]:
#실수를 원소로 갖는 NumPy 배열을 정수로 변환
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int) #반올림을 하는 것이 아닌 내림을 한다.
num_i1

array([10, 21,  0,  4,  5])

In [47]:
#NumPy 뱅ㄹ의 데이터 타입이 실수에서 정수로 바뀐 것을 볼수 있다.
print(num_f1.dtype)
print(num_i1.dtype)

float64
int64

## 난수 배열의 생성

- random 모듈을 이용해 임의의 숫자인 난수(random number)를 생성
- NumPy에서도 난수를 발생시킬 수 있는 다양한 함수
- 그중 rand() 함수를 이용하면 실수 난수를 요소로 갖는 NumPy배열을 생성할 수 있으며,
- randint()함수를 이용하면 정수 난수를 요소로 갖는 NumPy배열을 생성
 
 - rand_num = np.random.rand([d0,d1,...dn])
 - rand_num = np.random.randint([low,]high[,size])

- rand() 함수는 [0,1)사이의 실수 난숫를 갖는NumPy 배열을 생성
- [a,b) 표현은 값의 범위가 a이상이고 b미만이라는 의미
- a는 범위에 포함되고 b는 포함되지 않음
- randint()함수는 [low,high) 사이의 정수 난수를 갖는 배열을 생성
- size는 배열의 형태를 지정하는 것으로 (d0,d1,...dn)형식으로 입력
- low가 입력되지 않으면 0으로 간주하고, size가 입력되지 않으면 1로 간주한다.
- NumPy 에서 난수를 생성

In [50]:
#[0,1) 사이의 실수로 난수 배열을 생성하는 rand()
print(np.random.rand(2,3))
print('\n')
print(np.random.rand())
print('\n')
print(np.random.rand(2,3,4))

[[0.18240024 0.46402581 0.88056229]
 [0.62335624 0.90765673 0.88907987]]


0.3013010627778051


[[[0.08435206 0.05763618 0.93664463 0.22513807]
  [0.01254924 0.20341905 0.11217511 0.72674592]
  [0.98568679 0.98296297 0.93459601 0.71638856]]

 [[0.00257154 0.92142293 0.87997845 0.76867167]
  [0.79347576 0.46812117 0.14699042 0.64560661]
  [0.94531326 0.5709363  0.44777545 0.48965295]]]

In [69]:
#지정한 범위에 해당하는 정수로 난수 배열을 생성하는 randint()
print(np.random.randint(10,size=(3,4)),'\n')
print(np.random.randint(1,2))

[[4 8 2 7]
 [5 4 8 7]
 [2 1 7 1]]

1

## 배열의 연산

### 기본연산
- NumPy 배열은 다양하게 연산할 수 있음
- 배열의 형태(shape)가 같다면 덧셈과 뻴셈, 곱셈과 나눗셈을 연산할 수 있음

In [56]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,3,4,5])

- 배열의 형태가 같은 두 개의 1차원 배열을 생성
- 두 배열의 형태가 같다는 의미는 두 배열의 `ndarray.shape`의 결과가 같다는 의미
- 1차원 배열의 경우에는 두 배열의 원소 개수가 같다면 형태가 같은 배열
- 2차원 배열이라면 mxn행렬에서 두 행렬의 m과 n이 각각 같은 경우
- 두배열의 합은 각 배열의 같은 위치의 원소끼리 더함
- 두 NumPy 배열의 합을 구하는 예

In [70]:
arr1+arr2

array([11, 23, 34, 45])

In [71]:
# 두 배열의 합과 마찬가지로 두배열의 차도 같은 위치의 원소끼리 뺌
arr1-arr2

array([ 9, 17, 26, 35])

- 배열에 상수를 곱할 수도 있음
- 배열에 상수를 곱하면 각 원소에 상수를 곱함

In [72]:
arr2*2

array([ 2,  6,  8, 10])

- 배열의 거듭제곱도 할 수 있음
- 배열의 거듭제곱은 배열의 각 원소에 거듭제곱을 함

In [73]:
arr2 ** 2

array([ 1,  9, 16, 25])

In [74]:
#두 배열의 곱셈은 각 원소 끼리 곱합
arr1*arr2

array([ 10,  60, 120, 200])

In [75]:
#두 배열의 나눗셈은 각원소 끼리 나눔
arr1/arr2

array([10.        ,  6.66666667,  7.5       ,  8.        ])

In [76]:
#q배열의 복합 연산도 이용할수 있다.
arr1/(arr2**2)

array([10.        ,  2.22222222,  1.875     ,  1.6       ])

In [77]:
#배열은 비교 연산도 할 수 있음
#원소별로 조건과 일치하는지 검사한 후 일치하면 True 그렇지 않으면 False
arr1>20

array([False, False,  True,  True])

## 통계를 위한 연산
- NumPy에는 배열의 합, 평균, 표준편차, 분산, 최솟값, 최댓값, 누적합과 누적 곱 등 주로 통계에서 많이 이용하는 메서드들이 있다.
- 이메서드는 각각 sum(), std(), var(), min(), max(),cumsum(),cumprod()이다.

In [78]:
#배열의 생성
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [79]:
#배열의 합과 평균을 구함
print(arr3.sum())
print(arr3.mean())

10
2.0

In [80]:
# 배열의 최솟값과 최댓값을 구함
print(arr3.min())
print(arr3.max())

0
4

In [81]:
# 배열의 누적합과 누적곱을 구함
print(arr3.cumsum())
print(arr3.cumprod())

[ 0  1  3  6 10]
[0 0 0 0 0]

## 행렬 연산
- NumPy는 배열의 단순 연산뿐만 아니라 선형대수를 위한 행렬연산도 지원
- 다양한 기능중 행렬 곱 전치행렬, 역행렬, 행렬식을 구하는 방법
- 행렬 연산을 하기 위해 2x2행렬 A와B를 만듦

In [84]:
A=np.arange(0,4).reshape(2,2)
B=np.array([3,2,0,1]).reshape(2,2)

In [85]:
# 행렬곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [87]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [88]:
#전치행렬
A.transpose()
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [89]:
#역행렬
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [90]:
#행렬식
np.linalg.det(A)

-2.0

## 배열의 인덱싱과 슬라이싱
- NumPy에서는 배열의 위치, 조건, 범위를 지정해 배열에서 필요한 원소를 선택
- 배열에서 선택된 원소는 값을 가져오거나 변경
- 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것을 인덱싱(Indexing)
- 범위를 지정해 배열의 원소를 선택하는 것을 슬라이싱(Slicing)

### 배열의 인덱싱
- 1차원 배열에서 특정 위치의 원소를 선택하려면 원소의 위치를 지정
- 배열명[위치]
- 배열 원소의 위치는 0부터 시작
- 배열의 인덱싱 예를 살펴보기 위해 1차원 배열을 생성

In [91]:
a1 = np.array([0,10,20,30,40,50])

In [92]:
print(a1[0])
print(a1[4])
a1[5] = 70
print(a1)

0
40
[ 0 10 20 30 40 70]

- 1차원 배열에서 여러 개의 원소를 선택하려면 다음과 같이 지정
- 배열명[[위치1, 위치2,...위치n]]

In [93]:
# 1차원 배열 a1에서 1,3,4의 위치에 있는 원소 10,30,40을 가져옴
a1[[1,3,4]]

array([10, 30, 40])

-2차원 배열에서 특정 위치의 원소를 선택하려면 다음과 같이 행과 열의 위치를 지정
- 배열명[행_위치, 열_위치]
- 열_위치 없이 행위치만 이벽하면 지정한 행 전체가 선택된다.
- 2차원 배열에서 인덱싱으로 특정 원소를 선택해서 가져오는 예

In [95]:
#2차원 배열을 생성
a2 = np.arange(10, 100,10).reshape(3,3)
print(a2[0,2])
a2[2,2] = 95 # 2차원 배열의 행과 열의 위치를 지정해서 원소를 선택한 후 값을 변경
print(a2)
print(a2[1]) # 2차원 배열에서 행_위치를 지정해 행 전체를 가져옴

a2[1] = np.array([45,55,65])# 2차원 배열에서 행_위치를 지정해 행 전체를 가져와서 값을 변경
print(a2)
a2[1] = [47,57,67] # np.array를 사용하지 않고 리스트로 바로 값을 변경하는 것도 가능
print(a2)

30
[[10 20 30]
 [40 50 60]
 [70 80 95]]
[40 50 60]
[[10 20 30]
 [45 55 65]
 [70 80 95]]
[[10 20 30]
 [47 57 67]
 [70 80 95]]

- 2차원 배열의 여러 원소를 선택하기 위해서는 다음과 같이 지정
- 배열명[[행_위치1, 행_위치2,..,행_위치n],[열_위치1, 열_위치2, ..., 열_위치n]]
- 2차원 배열에서 행과 열의 위치를 지정해 여러 원소를 선택해서 가져오괴

In [96]:
# 2차원 배열 a2에서 (0,0)위치의 원소 10 [2,1] 위치의 원소 80을 선택해 가져옴
# 앞에는 무조건 행이고 뒤에가 열이다 같이 생각하면 안된다.
a2[[0,2],[0,1]]

array([10, 80])

- 배열에 조건을 지정해 조건을 만족하는 배열을 선택할 수도 있음
- 배열명[조건]
- 배열에서 조건을 만족하는 원소만 선택

In [97]:
#배열 a에서 a>3 조건을 만족하는 원소만 가져옴
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [99]:
#(a%2)==0 조건을 이용해 배열 a에서 짝수인 원소만을 선택하는 예
a[(a%2) ==0]

array([2, 4, 6])

## 배열의 슬라이싱
- 범위를 지정해 배열의 일부분을 선택하는 슬라이싱
- 1차원 배열의 경우 슬라이싱은 다음과 같이 배열의 시작과 끝 위치를 지정
- 배열[시작_위치:끝_위치]
- 시작위치를 지정하지 않으면 시작위치는 0이 되어 범위는 끝위치-1이 된다.
- 끝위치를 지정하지 않으면 끝위치는 배열의 길이가 되어 범위는 시작위치~배열의 끝 이된다.

In [100]:
# 1차원 배열에서 시작위차와 끝위치를 지정해서 슬라이싱 하는 예
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [101]:
#1차원 배열에서 시작위치와 끝위치를 지정하지 않고 슬라이싱하는 예
print(b1[:3])
print(b1[2:])

[ 0 10 20]
[20 30 40 50]

In [102]:
#슬라이싱을 이용해 원소를 가져올 수 있을 뿐만 아니라 원소를 변경도 가능하다.
b1[2:5] = np.array([25,35,46])
b1

array([ 0, 10, 25, 35, 46, 50])

In [103]:
#여러 원소의 값을 같은 값으로 변경하려면 하나의 값을 지정해 변경할 수 있음
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

- 2차원 배열(행렬)의 경우 슬라이싱은 다음과 같이 행과 열의 시작과 끝 위치를 지정
- 배열[행시작위치:행끝위치,열시작위치:열끝위치]
- 원소의 행 범위는 행시작위치~행끝위치-1이 되고 열범위는 열시작위치~ 열끝위치-1이 된다.
- 행시작위치나 열 시작위치를 생략하면 시작위치는 0
- 행 끝위치나 열 끝위치를 생략하면 각각끝으로 지정
- 특정 행을 선택한 후 열을 슬라이싱하려면 다음과 같이 행의 위치를 지정하고 열의 시작과 끝 위치를 지정한다.
- 배열[행위치][열시작위치:열끝위치]

In [104]:
#2차원 배열 생성
b2= np.arange(10,100,10).reshape(3,3)
# 2차원 배열에서 행시작위치:행끝위치, 열시작위치:열끝위치를 지정해 슬라이싱
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [105]:
#2차원 배열을 슬라이싱할때 일부를 생락한예
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [106]:
#2차원 배열에서 행을 지정하고 열을 슬라이싱하는 예
b2[1][0:2]

array([40, 50])

In [108]:
#1차원 배열에서와 마찬가지로 다음과 같이 2차원 배열에서도 슬라이싱 된 배열에 값을 지정할 수 있음
b2[0:2, 1:3]=np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])